<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
	<TargetFrameworks>net9.0;net9.0-maccatalyst18.4</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
	<ServerGarbageCollection>false</ServerGarbageCollection>
	<RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
	<TargetFramework>net9.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
	<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.5" />
  </ItemGroup>

</Project>
