name: Prepare Build Artifacts

on:
  push:
    branches: [ release ]

jobs:
  build-blazor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Build Blazor App
        run: |
          cd src/BullseyeApp
          dotnet publish -c Release -o ../../bullseye-blazor
      - name: Add static.json
        run: |
          echo '{ 
            "root": "index.html",
            "clean_urls": true,
            "routes": {
              "/**": "index.html"
            }
          }' > static.json

  build-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Build .NET Worker
        run: |
          cd src/BullseyeWorker
          dotnet publish -c Release -o ../../bullseye-worker
      - name: Create Procfile for Worker
        run: echo 'worker: dotnet bullseye-worker/BullseyeWorker.dll' > Procfile

  prepare-django:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Move Django App
        run: |
          mkdir -p bullseye-platform
          cp -r src/site/* bullseye-platform/
