name: Build and Release App
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: src/BullseyeApp

      - name: Build Application
        run: dotnet build --configuration Release --no-restore
        working-directory: src/BullseyeApp

      - name: Publish Application
        run: dotnet publish -c Release -o output
        working-directory: src/BullseyeApp

      - name: Create ZIP Archive
        run: Compress-Archive -Path output/* -DestinationPath bullseye-release.zip
        working-directory: src/BullseyeApp

      - name: List App Directory
        run: ls
        working-directory: src/BullseyeApp

      - name: List Output Directory
        run: ls output/
        working-directory: src/BullseyeApp

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bullseye-release
          path: src/BullseyeApp/bullseye-release.zip
          compression-level: 7

  release:
    needs: build
    runs-on: windows-latest
    steps:
       
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: bullseye-release
          path: src/BullseyeApp/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: src/BullseyeApp/bullseye-release.zip
